spring.datasource.jdbcUrl = jdbc:mysql://localhost:3306/eatsdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 
 
server.port=8082
## Hibernate Properties added
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.batch_size=4
#server.port=8085

logging.level.org.springframework=INFO
spring.datasource.db.jdbcUrl = jdbc:mysql://localhost:3306/sys?useSSL=false
spring.datasource.db.username = root
spring.datasource.db.password = root
spring.classformat.ignore=true
#spring.ai.ollama.model=chatgpt
spring.ai.ollama.model=mistral
spring.ai.ollama.base-url=http://localhost:11434

