server:
  port: 8082

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/eatsdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        order_inserts: true
        jdbc:
          batch_size: 4
    data:
      redis:
        host: localhost
        port: 6379
    cache:
     type: redis

  ai:
    ollama:
      model: mistral
      base-url: http://localhost:11434

logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,httptrace
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    rateLimiterAspectOrder: 3
    instances:
      paymentService:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
  retry:
    retryAspectOrder: 2
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      paymentService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password:  9kC862i8J7VeTgCS9JU8z70D

xpack.security.http.ssl.enabled: false



roles:
  roles:
    Developer:
      - DB_READ
      - APP_READ
      - LOG_VIEW

    Admin:
      - DB_READ
      - DB_WRITE
      - APP_MANAGE
      - USER_MANAGE
      - LOG_VIEW
      - SYSTEM_CONFIG

    Intern:
      - APP_READ
      - DOC_VIEW

    Manager:
      - APP_READ
      - REPORT_VIEW
      - USER_APPROVE

    Auditor:
      - LOG_VIEW
      - REPORT_VIEW
      - COMPLIANCE_CHECK
